font_family      Hack
bold_font        Hack Bold
italic_font      Hack Italic
bold_italic_font Hack Bold Italic
font_size        12.0
ligatures        yes

# Transparency and blur
background_opacity    0.7
background_blur_radius 30

# Decorations
window_decoration     none

# Padding
window_padding_width  10
