# Options
set -sg terminal-overrides ",*:RGB"
set -g escape-time 0  # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keeps sequential numbering
set -g repeat-time 2000  # increase prefix time

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix `
bind ` send-prefix


# Easier Reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Vim pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Keybindings: disable repeat for arrows
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R

# Keybindings: split
bind h split-window -h
bind | split-window -h
bind v split-window -v
bind - split-window -v

# Keybindings: other
bind f resize-pane -Z
bind q detach-client
bind e choose-window -Z

# Transparent bar
set -g status-style "bg=default,fg=#AAAAAA"

# No left/right text
set -g status-left "🍥"
set -g status-right ""

# Inactive windows
setw -g window-status-format \
"#[fg=#666666] #I:#W "

# Active window
setw -g window-status-current-format \
"#[fg=#FFFFFF,bold] #I:#W "

# Borders
set -g pane-border-style fg=#444444
set -g pane-active-border-style fg=#55FFFF
